site_name: CS basic notes
# site_url: https://csdiy.wiki/
site_url: https://emma-ssq.github.io/blog/
site_author: Emmassq
site_description: >-
  CS basic notes

repo_name: blog
repo_url: https://github.com/Emma-ssq/blog/

copyright: Copyright &copy; 2021-present <a href="https://github.com/Emma-ssq" target="_blank" rel="noopener noreferrer">Emma-ssq</a>

theme:
  name: material
  language: zh
  static_templates:
    - 404.html
  # favicon: images/favicon16x16.png
  favicon: images/winnie-pooh.png
  include_search_page: false
  search_index_only: true

  features:
    - header.autohide
    # - navigation.instant
    # - navigation.expand
    # - navigation.sections
    - navigation.tracking
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    # - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
    - content.code.annotate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

  custom_dir: overrides

markdown_extensions:
  - attr_list
  - md_in_html

plugins:
  - i18n:
      default_language: zh
      material_alternate: true
      languages:
        zh:
          name: 简体中文
          build: true
        en:
          name: English
          build: true
          site_name: Emma-ssq.blog
      nav_translations:
        en:
          前言: Foreword
          代码规范: Style Guides
          终端命令: Terminal instructions
          小白入门: Beginner Courses
          各类编程软件命令: Commands of Programming softwares
          debug博客: Blogs of debugging
          待实现: To Achieve
          实用工具: Productivity Toolkit
  - search:
      lang: ja
  - git-revision-date-localized
  - minify:
      minify_html: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Emma-ssq/blog/
  analytics:
    provider: google
    property: G-KJB4RXSKZG

nav:
  - 前言: "index.md"
  - 代码规范: "代码规范/代码规范.md"
  - 实用工具:
    - 科学上网: "tools/科学上网.md"
    - Vim: "tools/vim.md"
    - Git: "tools/Git.md"
    - GitHub: "tools/GitHub.md"
    - Typora: "tools/Typora.md"
    - VSCode: "tools/VSCode.md"
    - 其他好用软件: "tools/其他好用软件.md"
  - 终端命令: "命令/终端命令.md"
  - 编程软件操作及命令:
    - anaconda: "命令/anaconda.md"
  - debug博客:
    - mkdocs与github-actions搭建网站: "blogs/mkdocs与github-actions搭建网站.md"
  - 小白入门: 
    - "MIT-Missing-Semester": "小白入门/MIT-Missing-Semester.md"
  - ToAchieve: "ToAchieve.md"

  